# Name of the GitHub Actions
name: slack noti test
 
# Set the actions that triggers the workflow
on:
# Trigger the workflow on the push event, only in dev branch
  push:
    branches: [ master ]
 
 
jobs:
  build:
    runs-on: ubuntu-latest
 
 
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
       
 
    steps:
      # Check out the repo, so the job can access it.  
      - uses: actions/checkout@v2
 
 
      # Install Node on the runner
      - name: Use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v1
       
      # Install newman globally, the reporter for slack and install the html extra reporter
      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-slackreporter
         npm install -g newman-reporter-htmlextra
 
 
      # Create directory to upload test results
      - name: Make Directory for Test Results
        run: mkdir -p testArtifacts
 
 
      # Run postman collection
      - name: Run Postman Collection        
        run: |
 
        newman  run ./tests/payment-backend-collection.json -e ./tests/payment-backend-collection-env.json  --suppress-exit-code -r slackreporter,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html --reporter-slackreporter-webhookurl ${{ secrets.SLACK_BOT_TOKEN }}
     
      # Upload the reports to TestArtifacts directory
      - name: Output the results
        uses: actions/upload-artifact@v2
        with:
         name: Reports
         path: testArtifacts
